# Generated by Django 5.1.4 on 2025-01-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="name"),
            preserve_default=False,
        ),
    ]
