# Generated by Django 5.1.4 on 2025-01-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_apitoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="name",
            field=models.CharField(default="New", max_length=200),
        ),
    ]
